### ISSUE TITLE
Module name doesn't match directory

### ISSUE THREAD

**Issue by minorOffense** [OPLBPO/opl_browse#1]
The name of the module repo should match the file name pattern. So the files / functions should be opl_browse and not "browse".

You just need to pick one, but "browse" may conflict with a contrib module (doesn't right now).

Anyways, pick one please.

**Comment by crawleyde** [comment]
Thanks, I'll change it.

**Comment by crawleyde** [comment]
I see this also applies to opl_database feature, which should be opl_databases. I'll change that as well.
